// Auto-generated. Do not edit!

// (in-package object_manipulation_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let GraspHandPostureExecutionResult = require('./GraspHandPostureExecutionResult.js');
let actionlib_msgs = _finder('actionlib_msgs');
let std_msgs = _finder('std_msgs');

//-----------------------------------------------------------

class GraspHandPostureExecutionActionResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.header = null;
      this.status = null;
      this.result = null;
    }
    else {
      if (initObj.hasOwnProperty('header')) {
        this.header = initObj.header
      }
      else {
        this.header = new std_msgs.msg.Header();
      }
      if (initObj.hasOwnProperty('status')) {
        this.status = initObj.status
      }
      else {
        this.status = new actionlib_msgs.msg.GoalStatus();
      }
      if (initObj.hasOwnProperty('result')) {
        this.result = initObj.result
      }
      else {
        this.result = new GraspHandPostureExecutionResult();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type GraspHandPostureExecutionActionResult
    // Serialize message field [header]
    bufferOffset = std_msgs.msg.Header.serialize(obj.header, buffer, bufferOffset);
    // Serialize message field [status]
    bufferOffset = actionlib_msgs.msg.GoalStatus.serialize(obj.status, buffer, bufferOffset);
    // Serialize message field [result]
    bufferOffset = GraspHandPostureExecutionResult.serialize(obj.result, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type GraspHandPostureExecutionActionResult
    let len;
    let data = new GraspHandPostureExecutionActionResult(null);
    // Deserialize message field [header]
    data.header = std_msgs.msg.Header.deserialize(buffer, bufferOffset);
    // Deserialize message field [status]
    data.status = actionlib_msgs.msg.GoalStatus.deserialize(buffer, bufferOffset);
    // Deserialize message field [result]
    data.result = GraspHandPostureExecutionResult.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += std_msgs.msg.Header.getMessageSize(object.header);
    length += actionlib_msgs.msg.GoalStatus.getMessageSize(object.status);
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'object_manipulation_msgs/GraspHandPostureExecutionActionResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '6434d1842053adb9e907efbf917fa72b';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    Header header
    actionlib_msgs/GoalStatus status
    GraspHandPostureExecutionResult result
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    # 0: no frame
    # 1: global frame
    string frame_id
    
    ================================================================================
    MSG: actionlib_msgs/GoalStatus
    GoalID goal_id
    uint8 status
    uint8 PENDING         = 0   # The goal has yet to be processed by the action server
    uint8 ACTIVE          = 1   # The goal is currently being processed by the action server
    uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing
                                #   and has since completed its execution (Terminal State)
    uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)
    uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due
                                #    to some failure (Terminal State)
    uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,
                                #    because the goal was unattainable or invalid (Terminal State)
    uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing
                                #    and has not yet completed execution
    uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,
                                #    but the action server has not yet confirmed that the goal is canceled
    uint8 RECALLED        = 8   # The goal received a cancel request before it started executing
                                #    and was successfully cancelled (Terminal State)
    uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be
                                #    sent over the wire by an action server
    
    #Allow for the user to associate a string with GoalStatus for debugging
    string text
    
    
    ================================================================================
    MSG: actionlib_msgs/GoalID
    # The stamp should store the time at which this goal was requested.
    # It is used by an action server when it tries to preempt all
    # goals that were requested before a certain time
    time stamp
    
    # The id provides a way to associate feedback and
    # result message with specific goal requests. The id
    # specified must be unique.
    string id
    
    
    ================================================================================
    MSG: object_manipulation_msgs/GraspHandPostureExecutionResult
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # the result of the action
    ManipulationResult result
    
    
    ================================================================================
    MSG: object_manipulation_msgs/ManipulationResult
    # Result codes for manipulation tasks
    
    # task completed as expected
    # generally means you can proceed as planned
    int32 SUCCESS = 1
    
    # task not possible (e.g. out of reach or obstacles in the way)
    # generally means that the world was not disturbed, so you can try another task
    int32 UNFEASIBLE = -1
    
    # task was thought possible, but failed due to unexpected events during execution
    # it is likely that the world was disturbed, so you are encouraged to refresh
    # your sensed world model before proceeding to another task
    int32 FAILED = -2
    
    # a lower level error prevented task completion (e.g. joint controller not responding)
    # generally requires human attention
    int32 ERROR = -3
    
    # means that at some point during execution we ended up in a state that the collision-aware
    # arm navigation module will not move out of. The world was likely not disturbed, but you 
    # probably need a new collision map to move the arm out of the stuck position
    int32 ARM_MOVEMENT_PREVENTED = -4
    
    # specific to grasp actions
    # the object was grasped successfully, but the lift attempt could not achieve the minimum lift distance requested
    # it is likely that the collision environment will see collisions between the hand/object and the support surface
    int32 LIFT_FAILED = -5
    
    # specific to place actions
    # the object was placed successfully, but the retreat attempt could not achieve the minimum retreat distance requested
    # it is likely that the collision environment will see collisions between the hand and the object
    int32 RETREAT_FAILED = -6
    
    # indicates that somewhere along the line a human said "wait, stop, this is bad, go back and do something else"
    int32 CANCELLED = -7
    
    # the actual value of this error code
    int32 value
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new GraspHandPostureExecutionActionResult(null);
    if (msg.header !== undefined) {
      resolved.header = std_msgs.msg.Header.Resolve(msg.header)
    }
    else {
      resolved.header = new std_msgs.msg.Header()
    }

    if (msg.status !== undefined) {
      resolved.status = actionlib_msgs.msg.GoalStatus.Resolve(msg.status)
    }
    else {
      resolved.status = new actionlib_msgs.msg.GoalStatus()
    }

    if (msg.result !== undefined) {
      resolved.result = GraspHandPostureExecutionResult.Resolve(msg.result)
    }
    else {
      resolved.result = new GraspHandPostureExecutionResult()
    }

    return resolved;
    }
};

module.exports = GraspHandPostureExecutionActionResult;
