set(collision_avoidance_pick_and_place_MESSAGE_FILES "")
set(collision_avoidance_pick_and_place_SERVICE_FILES "/home/jyk/perception_driven_ws/src/collision_avoidance_pick_and_place/srv/GetTargetPose.srv")
