// Generated by gencpp from file robot_io/DigitalOutputUpdate.msg
// DO NOT EDIT!


#ifndef ROBOT_IO_MESSAGE_DIGITALOUTPUTUPDATE_H
#define ROBOT_IO_MESSAGE_DIGITALOUTPUTUPDATE_H

#include <ros/service_traits.h>


#include <robot_io/DigitalOutputUpdateRequest.h>
#include <robot_io/DigitalOutputUpdateResponse.h>


namespace robot_io
{

struct DigitalOutputUpdate
{

typedef DigitalOutputUpdateRequest Request;
typedef DigitalOutputUpdateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DigitalOutputUpdate
} // namespace robot_io


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::robot_io::DigitalOutputUpdate > {
  static const char* value()
  {
    return "5decc6a45bba41be52c4b7de53de20e7";
  }

  static const char* value(const ::robot_io::DigitalOutputUpdate&) { return value(); }
};

template<>
struct DataType< ::robot_io::DigitalOutputUpdate > {
  static const char* value()
  {
    return "robot_io/DigitalOutputUpdate";
  }

  static const char* value(const ::robot_io::DigitalOutputUpdate&) { return value(); }
};


// service_traits::MD5Sum< ::robot_io::DigitalOutputUpdateRequest> should match 
// service_traits::MD5Sum< ::robot_io::DigitalOutputUpdate > 
template<>
struct MD5Sum< ::robot_io::DigitalOutputUpdateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::robot_io::DigitalOutputUpdate >::value();
  }
  static const char* value(const ::robot_io::DigitalOutputUpdateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_io::DigitalOutputUpdateRequest> should match 
// service_traits::DataType< ::robot_io::DigitalOutputUpdate > 
template<>
struct DataType< ::robot_io::DigitalOutputUpdateRequest>
{
  static const char* value()
  {
    return DataType< ::robot_io::DigitalOutputUpdate >::value();
  }
  static const char* value(const ::robot_io::DigitalOutputUpdateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::robot_io::DigitalOutputUpdateResponse> should match 
// service_traits::MD5Sum< ::robot_io::DigitalOutputUpdate > 
template<>
struct MD5Sum< ::robot_io::DigitalOutputUpdateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::robot_io::DigitalOutputUpdate >::value();
  }
  static const char* value(const ::robot_io::DigitalOutputUpdateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::robot_io::DigitalOutputUpdateResponse> should match 
// service_traits::DataType< ::robot_io::DigitalOutputUpdate > 
template<>
struct DataType< ::robot_io::DigitalOutputUpdateResponse>
{
  static const char* value()
  {
    return DataType< ::robot_io::DigitalOutputUpdate >::value();
  }
  static const char* value(const ::robot_io::DigitalOutputUpdateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_IO_MESSAGE_DIGITALOUTPUTUPDATE_H
