; Auto-generated. Do not edit!


(cl:in-package object_manipulation_msgs-msg)


;//! \htmlinclude GraspHandPostureExecutionFeedback.msg.html

(cl:defclass <GraspHandPostureExecutionFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass GraspHandPostureExecutionFeedback (<GraspHandPostureExecutionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GraspHandPostureExecutionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GraspHandPostureExecutionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name object_manipulation_msgs-msg:<GraspHandPostureExecutionFeedback> is deprecated: use object_manipulation_msgs-msg:GraspHandPostureExecutionFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GraspHandPostureExecutionFeedback>) ostream)
  "Serializes a message object of type '<GraspHandPostureExecutionFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GraspHandPostureExecutionFeedback>) istream)
  "Deserializes a message object of type '<GraspHandPostureExecutionFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GraspHandPostureExecutionFeedback>)))
  "Returns string type for a message object of type '<GraspHandPostureExecutionFeedback>"
  "object_manipulation_msgs/GraspHandPostureExecutionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GraspHandPostureExecutionFeedback)))
  "Returns string type for a message object of type 'GraspHandPostureExecutionFeedback"
  "object_manipulation_msgs/GraspHandPostureExecutionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GraspHandPostureExecutionFeedback>)))
  "Returns md5sum for a message object of type '<GraspHandPostureExecutionFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GraspHandPostureExecutionFeedback)))
  "Returns md5sum for a message object of type 'GraspHandPostureExecutionFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GraspHandPostureExecutionFeedback>)))
  "Returns full string definition for message of type '<GraspHandPostureExecutionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# empty for now~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GraspHandPostureExecutionFeedback)))
  "Returns full string definition for message of type 'GraspHandPostureExecutionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# empty for now~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GraspHandPostureExecutionFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GraspHandPostureExecutionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'GraspHandPostureExecutionFeedback
))
